version: "3.9"

services:
  php-apache:
    image: php8.1-apache-mailhog
    build: ./.docker
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
      - ./.docker/php.ini:/usr/local/etc/php/php.ini
    command: sh -c 'composer update && apachectl -D FOREGROUND'

  mail:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

networks:
  dendrofen_php_mail_network:
    external: true
